name: Deploy to GitHub Pages
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install emscripten
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: 4.0.4
          actions-cache-folder: 'emsdk-cache'
      - name: Verify emscripten installation
        run: emcc -v
      - name: Build
        run: ./build.sh
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./web
